[selection]
fg = "light_yellow"
bold = true

[visual_mode_selection]
fg = "light_red"
bold = true

[selection.prefix]
prefix = "  "
size = 2

[executable]
fg = "light_green"
bold = true

[regular]
fg = "white"

[directory]
fg = "light_magenta"
bold = true

[link]
fg = "cyan"
bold = true

[link_invalid]
fg = "red"
bold = true

[socket]
fg = "light_blue"
bold = true

[ext]

bmp.fg = "yellow"
gif.fg = "yellow"
heic.fg = "yellow"
jpg.fg = "yellow"
jpeg.fg = "yellow"
pgm.fg = "yellow"
png.fg = "yellow"
ppm.fg = "yellow"
svg.fg = "yellow"

wav.fg = "blue"
flac.fg = "blue"
mp3.fg = "blue"
amr.fg = "blue"

avi.fg = "blue"
flv.fg = "blue"
m3u.fg = "blue"
m4a.fg = "blue"
m4v.fg = "blue"
mkv.fg = "blue"
mov.fg = "blue"
mp4.fg = "blue"
mpg.fg = "blue"
rmvb.fg = "blue"
webm.fg = "blue"
wmv.fg = "blue"

7z.fg = "red"
bz2.fg = "red"
gz.fg = "red"
rar.fg = "red"
tar.fg = "red"
tgz.fg = "red"
xz.fg = "red"
zip.fg = "red"
